@baseUrl = http://localhost:3001

GET {{baseUrl}}/styles/1/curations

###

// 답글 등록
POST {{baseUrl}}/curations/15/comments
Content-Type: application/json

{
	"content": "아주 좋습니다!",
	"password": "testyongyong1"
}

###

//답글 수정
PUT {{baseUrl}}/comments/14
Content-Type: application/json

{
	"content": "string",
	"password": "string",
}

###

//답글 삭제
DELETE {{baseUrl}}/comments/12
Content-Type: application/json

{
	"password": "string",
}