@baseUrl = http://localhost:3000

GET {{baseUrl}}/styles/1/curations

###

// 답글 등록
POST {{baseUrl}}/curations/16/comments
Content-Type: application/json

{
	"content": "아주 좋습니다!",
	"password": "pwpwpwpw5"
}

###

//답글 수정
PUT {{baseUrl}}/comments/16
Content-Type: application/json

{
	"content": "스타일이 정말 좋아요!",
	"password": "pwpwpwpw5"
}

###

//답글 삭제
DELETE {{baseUrl}}/comments/16
Content-Type: application/json

{
	"password": "pwpwpwpw5"
}