GET http://localhost:3000/styles?page=1&pageSize=13

// 최신순, 조회순, 큐레이팅순(큐레이팅 많은 순)-정렬 
###
GET http://localhost:3000/styles?sortBy=oldest
###
GET http://localhost:3000/styles?sortBy=mostViewed
###
GET http://localhost:3000/styles?sortBy=mostCurated

//닉네임, 제목, 상세, 태그 검색 
###
GET http://localhost:3000/styles?searchBy=nickname&keyword=sora
###
GET http://localhost:3000/styles?searchBy=nickname&keyword=sooyoung
###
GET http://localhost:3000/styles?searchBy=title&keyword=겨울
###
GET http://localhost:3000/styles?searchBy=content&keyword=팬츠
###
GET http://localhost:3000/styles?searchBy=tag&keyword=린넨





//태그 검색 
###
GET http://localhost:3000/styles?tag=미니멀

// 인기 태그 조회
###
GET http://localhost:3000/tags
###
// 보고 싶은 인기 태그 갯수 지정 가능
GET http://localhost:3000/tags?n=10




//스타일 상세 조회
###
GET http://localhost:3000/styles/12




###
POST http://localhost:3000/styles
Content-Type: application/json

{
	"nickname": "닉네임테스트끝",
	"title": "타이틀테스트끝",
	"content": "콘텐트테스트끝",
	"password": "testComplete1",
	"categories": {
		"TOP": {
			"name": "카테고리네임테스트완",
			"brand": "브랜드테스트완료",
			"price": 35000
		},
		"BOTTOM": {
			"name": "트레이닝바지",
			"brand": "오프화이트",
			"price": 500000
		}
	},
	"tags": [
		"태그길이테스트해보겠습니다과연잘작동될지",
		"길이도검사하고개수도검사해야하는데",
		"밥먹으러가려면돼야해"
	],
	"imageUrls": [
		"https://placehold.co/600x400/EEE/31343C?text=Image+1",
    "https://placehold.co/600x400/CCC/31343C?text=Image+2"
	]
}


###

PUT http://localhost:3000/styles/27
Content-Type: application/json

{
	"nickname": "수정테스트합니다",
	"title": "수정테스트..",
	"content": "수정테스트중",
	"password": "testComplete1",
	"categories": {
		"TOP": {
			"name": "후드티",
			"brand": "메종키츠네",
			"price": 350000
		},
		"BOTTOM": {
			"name": "트레이닝바지",
			"brand": "오프화이트",
			"price": 500000
		}
	},
	"tags": [
		"겨울맞이",
		"편한룩"
	],
	"imageUrls": [
		"https://placehold.co/600x400/EEE/31343C?text=Image+1",
    "https://placehold.co/600x400/CCC/31343C?text=Image+2"
	]
}

###
DELETE http://localhost:3000/styles/18
Content-Type: application/json

{
  "password": "test123123"
}